{{- if .Values.api.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aether-grid.api.serviceAccountName" . }}
  namespace: {{ include "aether-grid.namespace" . }}
  labels:
    {{- include "aether-grid.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
