{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aether-api
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    {{- include "aether-grid.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  namespaceSelector:
    matchNames:
      - {{ include "aether-grid.namespace" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: aether-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aether-proxy
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    {{- include "aether-grid.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-plane
spec:
  namespaceSelector:
    matchNames:
      - {{ include "aether-grid.namespace" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: aether-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
