apiVersion: v1
kind: Service
metadata:
  name: aether-proxy
  namespace: aether-grid
  labels:
    app.kubernetes.io/name: aether-proxy
    app.kubernetes.io/part-of: aether-grid
    app.kubernetes.io/component: data-plane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aether-proxy
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
