package com.suplab.aether.agents.spi;

public enum AgentCapability {
    GOVERNANCE,
    RETRY_STRATEGY,
    HALLUCINATION_DETECTION,
    POLICY_DRIFT,
    TEMPORAL_PREDICTION,
    REFLECTION,
    EMBEDDING,
    SELF_IMPROVEMENT,
    PERSONAL_CONTEXT_ENRICHMENT
}
