apiVersion: v1
kind: Service
metadata:
  name: aether-api
  namespace: aether-grid
  labels:
    app.kubernetes.io/name: aether-api
    app.kubernetes.io/part-of: aether-grid
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aether-api
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
