{{- if .Values.proxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aether-grid.proxy.serviceAccountName" . }}
  namespace: {{ include "aether-grid.namespace" . }}
  labels:
    {{- include "aether-grid.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-plane
  {{- with .Values.proxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
